name: "Build"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build_docker_image:
    name: ${{ github.event_name == 'pull_request' && 'Build' || 'Build & Push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/jorenn92/maintainerr

      - name: Log in to GitHub Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: ${{ github.event_name == 'pull_request' && 'Build image' || 'Build & Push image' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            GIT_SHA=${{ github.sha }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            jorenn92/maintainerr:develop
          labels: ${{ steps.meta.outputs.labels }}

  build_artifacts:
    name: ${{ github.event_name == 'pull_request' && 'Build' || 'Build & Push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install turbo
        run: yarn global add turbo@^2

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn turbo build

      - name: Prepare Artifact
        shell: bash
        run: |
          mkdir _output
          cp -r ui/.next/standalone/ui _output/ui
          cp -r ui/.next/static _output/ui/.next/static
          cp -r ui/public _output/ui/public
          cp -r server/dist _output/server
          cp -r server/node_modules _output/server/node_modules

      - name: Publish UI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_ui
          path: _output/