name: "Release PR"

on:
  issue_comment:
    types:
      - created

jobs:
  build-docker-image:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/release-pr') }}
    name: Build and push docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/jorenn92/maintainerr

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build & Push docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            GIT_SHA=${{ github.sha }}
          tags: |
            ghcr.io/jorenn92/maintainerr:pr-${{ github.event.issue.number }}-${{ steps.vars.outputs.sha_short }}
            jorenn92/maintainerr:pr-${{ github.event.issue.number }}-${{ steps.vars.outputs.sha_short }}
          labels: ${{ steps.meta.outputs.labels }}
